version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "thaim"
    labels:
      - "dependencies"
    commit-message:
      prefix: "cargo"
      include: "scope"