name: Pull Request Checks

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  title-check:
    name: Check PR Title Format
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title follows Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat      # include: perf
            fix
            docs
            refactor  # include: style
            test
            chore     # include: ci, build
            revert
          requireScope: false
